version: '3.9'

services:
  mariadb:
    image: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception

  wordpress:
    image: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception

  nginx:
    image: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge
    
volumes:
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device:  /home/amahdiou/data/mariadb
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o : bind
      device :  /home/amahdiou/data/wordpress