version: '3.9'

services:
  mariadb:
    image: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    # environment:
      # MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      # MYSQL_DATABASE: "${DB_NAME}"
      # MYSQL_USER: "${DB_USER}"
      # MYSQL_PASSWORD: "${DB_PASSWORD}"
    expose:
      - "3306"
    networks:
      - inception

  wordpress:
    image: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - inception

  nginx:
    image: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge
