#!/bin/bash
echo "FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS $DB_NAME;

CREATE USER $DB_USE @'%' IDENTIFIED BY $DB_PASSWORD;

ALTER USER 'root'@'localhost' IDENTIFIED BY '0900';

GRANT ALL PRIVILEGES ON *.* TO $DB_USER @'%'IDENTIFIED BY $DB_PASSWORD;
FLUSH PRIVILEGES; " > exec.txt

mariadbd --user=mysql --bootstrap < exec.txt

exec "$@"